import { useState, useMemo } from "react";
import ToolLayout from "../../components/ToolLayout";

// Presets for Schema Generator
const SCHEMA_TYPES = [
  { id: "article", label: "Article Schema" },
  { id: "faq", label: "FAQ Page Schema" },
  { id: "product", label: "Product Schema" },
  { id: "local-business", label: "Local Business Schema" },
  { id: "review", label: "Review Rating Schema" },
  { id: "breadcrumb", label: "Breadcrumb List Schema" },
  { id: "event", label: "Event Schema" },
  { id: "recipe", label: "Recipe Schema" }
];

function SiteConfigurationStudio({ initialTab = "robots" }) {
  const [activeTab, setActiveTab] = useState(initialTab);

  // 1. Robots.txt Generator & Validator
  const [robotsAgent, setRobotsAgent] = useState("*");
  const [crawlDelay, setCrawlDelay] = useState("none");
  const [sitemapLink, setSitemapLink] = useState("https://example.com/sitemap.xml");
  const [disallowPath, setDisallowPath] = useState("/admin/");
  const [testRobotsInput, setTestRobotsInput] = useState(`User-agent: *\nDisallow: /admin/\nDisallow: /private/`);
  const [testUrlPath, setTestUrlPath] = useState("/admin/dashboard");
  const [robotsTestResult, setRobotsTestResult] = useState("");

  const generatedRobots = `# Robots.txt generated by UtilsFlow
User-agent: ${robotsAgent}
${disallowPath ? `Disallow: ${disallowPath}` : ""}
${crawlDelay !== "none" ? `Crawl-delay: ${crawlDelay}` : ""}
${sitemapLink ? `Sitemap: ${sitemapLink}` : ""}`;

  function testRobotsRules() {
    const lines = testRobotsInput.split("\n").map(l => l.trim().toLowerCase());
    let isBlocked = false;
    let currentAgentMatch = false;

    for (const line of lines) {
      if (line.startsWith("user-agent:")) {
        const agent = line.replace("user-agent:", "").trim();
        if (agent === "*" || agent === "googlebot") {
          currentAgentMatch = true;
        } else {
          currentAgentMatch = false;
        }
      }
      if (currentAgentMatch && line.startsWith("disallow:")) {
        const path = line.replace("disallow:", "").trim();
        if (path && testUrlPath.toLowerCase().startsWith(path)) {
          isBlocked = true;
          break;
        }
      }
    }

    setRobotsTestResult(isBlocked ? "❌ Blocked by Robots.txt Rules" : "✅ Allowed / Crawlable");
  }

  // 2. XML Sitemap Generator & URL Extractor / Validator
  const [sitemapUrls, setSitemapUrls] = useState("https://example.com/\nhttps://example.com/about\nhttps://example.com/contact");
  const [sitemapFreq, setSitemapFreq] = useState("weekly");
  const [includeImages, setIncludeImages] = useState(false);
  const [imageUrlMap, setImageUrlMap] = useState("https://example.com/logo.png");
  const [generatedSitemap, setGeneratedSitemap] = useState("");
  const [rawXmlToExtract, setRawXmlToExtract] = useState("");
  const [extractedUrls, setExtractedUrls] = useState([]);
  const [sitemapValidationResult, setSitemapValidationResult] = useState("");

  function buildSitemap() {
    const urls = sitemapUrls.split("\n").map(u => u.trim()).filter(Boolean);
    const dateStr = new Date().toISOString().split("T")[0];
    
    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
    if (includeImages) {
      xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n`;
    } else {
      xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
    }
    
    urls.forEach(url => {
      xml += `  <url>\n    <loc>${url}</loc>\n    <lastmod>${dateStr}</lastmod>\n    <changefreq>${sitemapFreq}</changefreq>\n    <priority>${url.endsWith("/") ? "1.0" : "0.8"}</priority>\n`;
      if (includeImages && imageUrlMap) {
        xml += `    <image:image>\n      <image:loc>${imageUrlMap}</image:loc>\n    </image:image>\n`;
      }
      xml += `  </url>\n`;
    });
    
    xml += `</urlset>`;
    setGeneratedSitemap(xml);
  }

  function validateXmlSitemap() {
    if (!rawXmlToExtract.trim()) {
      setSitemapValidationResult("⚠️ Please enter sitemap XML code to validate.");
      return;
    }
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(rawXmlToExtract, "application/xml");
      const parserError = doc.querySelector("parsererror");
      if (parserError) {
        setSitemapValidationResult(`❌ XML Parsing Error: ${parserError.textContent}`);
      } else {
        const urlElements = doc.getElementsByTagName("url");
        if (urlElements.length === 0) {
          setSitemapValidationResult("⚠️ Parsed successfully as XML but found no <url> tags inside.");
        } else {
          setSitemapValidationResult(`✅ Valid XML Sitemap: Found ${urlElements.length} URLs mapped.`);
        }
      }
    } catch (e) {
      setSitemapValidationResult(`❌ Parsing Exception: ${e.message}`);
    }
  }

  function extractUrlsFromXml() {
    const locRegex = /<loc>(.*?)<\/loc>/gi;
    const list = [];
    let match;
    while ((match = locRegex.exec(rawXmlToExtract)) !== null) {
      list.push(match[1].trim());
    }
    setExtractedUrls(list);
  }

  // 3. Schema JSON-LD Builder & Rich Results Tester
  const [schemaType, setSchemaType] = useState("article");
  
  // Dynamic fields
  const [articleTitle, setArticleTitle] = useState("My SEO Guide");
  const [articleAuthor, setArticleAuthor] = useState("John Doe");
  
  const [productName, setProductName] = useState("SEO Audit Tool");
  const [productPrice, setProductPrice] = useState("29.99");
  
  const [faqList, setFaqList] = useState([{ q: "What is Schema?", a: "Structured data formats." }]);
  
  // Local Business Fields
  const [bizName, setBizName] = useState("My Agency");
  const [bizAddress, setBizAddress] = useState("123 Main St, New York");
  const [bizPhone, setBizPhone] = useState("+1 555-5555");
  const [bizUrl, setBizUrl] = useState("https://myagency.com");

  // Review Rating Fields
  const [reviewItem, setReviewItem] = useState("Cool Product");
  const [reviewerName, setReviewerName] = useState("Alice");
  const [ratingValue, setRatingValue] = useState("4.5");
  const [bestRating, setBestRating] = useState("5");

  // Event Fields
  const [eventName, setEventName] = useState("Web Summit");
  const [eventDate, setEventDate] = useState("2026-10-15");
  const [eventLocation, setEventLocation] = useState("Lisbon Arena");

  // Recipe Fields
  const [recipeName, setRecipeName] = useState("Chocolate Chip Cookies");
  const [recipeAuthor, setRecipeAuthor] = useState("Chef Jane");
  const [recipePrepTime, setRecipePrepTime] = useState("PT15M");
  const [recipeCookTime, setRecipeCookTime] = useState("PT10M");

  // Breadcrumb List Fields
  const [breadcrumbs, setBreadcrumbs] = useState([
    { name: "Home", url: "https://example.com/" },
    { name: "Blog", url: "https://example.com/blog" }
  ]);

  // Schema verification output
  const [testSchemaInput, setTestSchemaInput] = useState("");
  const [schemaTestResult, setSchemaTestResult] = useState("");

  const generatedSchemaText = useMemo(() => {
    let obj = {};

    if (schemaType === "article") {
      obj = {
        "@context": "https://schema.org",
        "@type": "NewsArticle",
        "headline": articleTitle,
        "datePublished": new Date().toISOString(),
        "author": {
          "@type": "Person",
          "name": articleAuthor
        }
      };
    } else if (schemaType === "faq") {
      obj = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqList.map(item => ({
          "@type": "Question",
          "name": item.q,
          "acceptedAnswer": {
            "@type": "Answer",
            "text": item.a
          }
        }))
      };
    } else if (schemaType === "product") {
      obj = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": productName,
        "offers": {
          "@type": "Offer",
          "price": productPrice,
          "priceCurrency": "USD"
        }
      };
    } else if (schemaType === "local-business") {
      obj = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": bizName,
        "address": {
          "@type": "PostalAddress",
          "streetAddress": bizAddress
        },
        "telephone": bizPhone,
        "url": bizUrl
      };
    } else if (schemaType === "review") {
      obj = {
        "@context": "https://schema.org",
        "@type": "Review",
        "itemReviewed": {
          "@type": "Thing",
          "name": reviewItem
        },
        "author": {
          "@type": "Person",
          "name": reviewerName
        },
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": ratingValue,
          "bestRating": bestRating
        }
      };
    } else if (schemaType === "breadcrumb") {
      obj = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": breadcrumbs.map((b, idx) => ({
          "@type": "ListItem",
          "position": idx + 1,
          "name": b.name,
          "item": b.url
        }))
      };
    } else if (schemaType === "event") {
      obj = {
        "@context": "https://schema.org",
        "@type": "Event",
        "name": eventName,
        "startDate": eventDate,
        "location": {
          "@type": "Place",
          "name": eventLocation,
          "address": {
            "@type": "PostalAddress",
            "streetAddress": eventLocation
          }
        }
      };
    } else if (schemaType === "recipe") {
      obj = {
        "@context": "https://schema.org",
        "@type": "Recipe",
        "name": recipeName,
        "author": {
          "@type": "Person",
          "name": recipeAuthor
        },
        "prepTime": recipePrepTime,
        "cookTime": recipeCookTime
      };
    }

    return JSON.stringify(obj, null, 2);
  }, [
    schemaType, articleTitle, articleAuthor, productName, productPrice, faqList,
    bizName, bizAddress, bizPhone, bizUrl, reviewItem, reviewerName, ratingValue, bestRating,
    eventName, eventDate, eventLocation, recipeName, recipeAuthor, recipePrepTime, recipeCookTime,
    breadcrumbs
  ]);

  function testSchemaSyntax() {
    try {
      const parsed = JSON.parse(testSchemaInput);
      if (!parsed["@context"] || !parsed["@type"]) {
        setSchemaTestResult("⚠️ Parsed JSON but missing @context or @type properties.");
      } else {
        setSchemaTestResult(`✅ Valid Schema Markup: Found ${parsed["@type"]} schema!`);
      }
    } catch (e) {
      setSchemaTestResult(`❌ Invalid JSON formatting: ${e.message}`);
    }
  }

  function copyToClipboard(text) {
    navigator.clipboard.writeText(text);
    alert("Copied!");
  }

  return (
    <ToolLayout
      toolId="site-configuration-studio"
      title="Site Configurations Studio"
      description="Configure sitemaps, construct schema structured JSON-LD scripts, extract XML URLs, build robots.txt guidelines, and validate indexing instructions locally."
      path="/tools/site-configuration-studio"
      category="seo"
      categoryPath="/?cat=seo"
    >
      <div className="tool-box">
        {/* Nav tabs */}
        <div style={{ display: "flex", gap: "8px", overflowX: "auto", paddingBottom: "10px", marginBottom: "20px" }}>
          {[
            { id: "robots", label: "Robots.txt Studio" },
            { id: "sitemap", label: "XML Sitemap Studio" },
            { id: "schema", label: "Schema Builder" },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`btn-secondary ${activeTab === tab.id ? "btn-primary" : ""}`}
              style={{ fontSize: "13px", padding: "8px 14px", flexShrink: 0 }}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* 1. Robots.txt Studio */}
        {activeTab === "robots" && (
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }} className="editor-grid">
            {/* Generator */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                ⚙️ Robots.txt Generator
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="bot-ua-inp">User-Agent</label>
                  <input type="text" id="bot-ua-inp" className="input-field" value={robotsAgent} onChange={e => setRobotsAgent(e.target.value)} />
                </div>
                <div>
                  <label className="label" htmlFor="bot-disallow-inp">Disallow Path</label>
                  <input type="text" id="bot-disallow-inp" className="input-field" value={disallowPath} onChange={e => setDisallowPath(e.target.value)} />
                </div>
                <div>
                  <label className="label" htmlFor="bot-delay-sel">Crawl-Delay</label>
                  <select id="bot-delay-sel" className="input-field" value={crawlDelay} onChange={e => setCrawlDelay(e.target.value)}>
                    <option value="none">No Delay</option>
                    <option value="1">1 second</option>
                    <option value="2">2 seconds</option>
                    <option value="5">5 seconds</option>
                  </select>
                </div>
                <div>
                  <label className="label" htmlFor="bot-sm-inp">Sitemap URL</label>
                  <input type="text" id="bot-sm-inp" className="input-field" value={sitemapLink} onChange={e => setSitemapLink(e.target.value)} />
                </div>

                <div style={{ marginTop: "10px" }}>
                  <button className="btn-secondary" style={{ width: "100%", justifyContent: "center" }} onClick={() => copyToClipboard(generatedRobots)}>
                    📋 Copy robots.txt Code
                  </button>
                </div>
              </div>
            </div>

            {/* Tester Validator */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                🔬 Robots.txt Rule Validator
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="bot-val-inp">Paste Robots.txt Code</label>
                  <textarea id="bot-val-inp" className="input-field" rows="4" value={testRobotsInput} onChange={e => setTestRobotsInput(e.target.value)} />
                </div>
                <div>
                  <label className="label" htmlFor="bot-test-path">Path to test (e.g. /admin/settings)</label>
                  <input type="text" id="bot-test-path" className="input-field" value={testUrlPath} onChange={e => setTestUrlPath(e.target.value)} />
                </div>
                <button className="btn-primary" onClick={testRobotsRules} style={{ justifyContent: "center" }}>
                  ⚡ Test Block Status
                </button>

                {robotsTestResult && (
                  <div style={{
                    padding: "10px",
                    background: robotsTestResult.includes("Blocked") ? "rgba(244,67,54,0.15)" : "rgba(76,175,80,0.15)",
                    border: robotsTestResult.includes("Blocked") ? "1px solid #f44336" : "1px solid #4caf50",
                    borderRadius: "4px",
                    textAlign: "center",
                    fontWeight: 600,
                    fontSize: "14px",
                    color: robotsTestResult.includes("Blocked") ? "#ef5350" : "#81c784"
                  }}>
                    {robotsTestResult}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* 2. XML Sitemap Studio */}
        {activeTab === "sitemap" && (
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }} className="editor-grid">
            {/* Sitemap Generator */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                🌐 XML Sitemap Builder
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="sm-urls-inp">URLs List (one per line)</label>
                  <textarea id="sm-urls-inp" className="input-field" rows="3" value={sitemapUrls} onChange={e => setSitemapUrls(e.target.value)} />
                </div>
                <div>
                  <label className="label" htmlFor="sm-freq-sel">Update Frequency</label>
                  <select id="sm-freq-sel" className="input-field" value={sitemapFreq} onChange={e => setSitemapFreq(e.target.value)}>
                    <option value="daily">Daily</option>
                    <option value="weekly">Weekly</option>
                    <option value="monthly">Monthly</option>
                  </select>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                  <input type="checkbox" id="inc-img-chk" checked={includeImages} onChange={e => setIncludeImages(e.target.checked)} />
                  <label className="label" htmlFor="inc-img-chk" style={{ marginBottom: 0 }}>Create Image Sitemap tags</label>
                </div>
                {includeImages && (
                  <div>
                    <label className="label" htmlFor="img-url-map-inp">Image Loc URL</label>
                    <input type="text" id="img-url-map-inp" className="input-field" value={imageUrlMap} onChange={e => setImageUrlMap(e.target.value)} />
                  </div>
                )}
                <button className="btn-primary" onClick={buildSitemap} style={{ justifyContent: "center" }}>
                  ⚡ Build XML Sitemap
                </button>

                {generatedSitemap && (
                  <div style={{ marginTop: "10px" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "4px" }}>
                      <span style={{ fontSize: "12px", color: "var(--text-secondary)" }}>XML Output</span>
                      <button style={{ fontSize: "11px", padding: "2px 6px" }} className="btn-secondary" onClick={() => copyToClipboard(generatedSitemap)}>
                        Copy XML
                      </button>
                    </div>
                    <textarea className="input-field" style={{ fontFamily: "monospace", fontSize: "11px" }} readOnly rows="4" value={generatedSitemap} />
                  </div>
                )}
              </div>
            </div>

            {/* Sitemap Link Extractor / Validator */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                🔗 Sitemap URL Extractor & Validator
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="sm-extract-inp">Paste XML Sitemap Markup</label>
                  <textarea
                    id="sm-extract-inp"
                    className="input-field"
                    rows="4"
                    value={rawXmlToExtract}
                    onChange={e => setRawXmlToExtract(e.target.value)}
                    placeholder="Paste sitemap XML content here..."
                  />
                </div>
                <div style={{ display: "flex", gap: "10px" }}>
                  <button className="btn-secondary" onClick={validateXmlSitemap} style={{ flex: 1, justifyContent: "center" }}>
                    🔬 Validate Sitemap
                  </button>
                  <button className="btn-primary" onClick={extractUrlsFromXml} style={{ flex: 1, justifyContent: "center" }}>
                    🔍 Extract URLs
                  </button>
                </div>

                {sitemapValidationResult && (
                  <div style={{
                    padding: "8px",
                    background: sitemapValidationResult.includes("Valid") ? "rgba(76,175,80,0.15)" : "rgba(244,67,54,0.15)",
                    border: sitemapValidationResult.includes("Valid") ? "1px solid #4caf50" : "1px solid #f44336",
                    borderRadius: "4px",
                    textAlign: "center",
                    fontWeight: 600,
                    fontSize: "12px",
                    color: sitemapValidationResult.includes("Valid") ? "#81c784" : "#ef5350"
                  }}>
                    {sitemapValidationResult}
                  </div>
                )}

                {extractedUrls.length > 0 && (
                  <div>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "6px" }}>
                      <span style={{ fontSize: "13px", fontWeight: 600 }}>Extracted {extractedUrls.length} links:</span>
                      <button className="btn-secondary" style={{ fontSize: "11px", padding: "3px 8px" }} onClick={() => copyToClipboard(extractedUrls.join("\n"))}>
                        📋 Copy List
                      </button>
                    </div>
                    <div style={{
                      maxHeight: "100px",
                      overflowY: "auto",
                      background: "rgba(0,0,0,0.1)",
                      border: "1px solid var(--border)",
                      borderRadius: "var(--radius-sm)",
                      padding: "8px",
                      fontSize: "12px",
                      display: "flex",
                      flexDirection: "column",
                      gap: "4px"
                    }}>
                      {extractedUrls.map((lnk, i) => (
                        <div key={i} style={{ wordBreak: "break-all", color: "var(--text-secondary)" }}>{lnk}</div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* 3. Schema JSON-LD Builder */}
        {activeTab === "schema" && (
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }} className="editor-grid">
            {/* Schema inputs */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                📑 JSON-LD Schema Builder
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="schema-type-sel">Schema Type</label>
                  <select id="schema-type-sel" className="input-field" value={schemaType} onChange={e => setSchemaType(e.target.value)}>
                    {SCHEMA_TYPES.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}
                  </select>
                </div>

                {/* Article fields */}
                {schemaType === "article" && (
                  <>
                    <div>
                      <label className="label" htmlFor="art-title-inp">Article Title</label>
                      <input type="text" id="art-title-inp" className="input-field" value={articleTitle} onChange={e => setArticleTitle(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="art-auth-inp">Author Name</label>
                      <input type="text" id="art-auth-inp" className="input-field" value={articleAuthor} onChange={e => setArticleAuthor(e.target.value)} />
                    </div>
                  </>
                )}

                {/* Product fields */}
                {schemaType === "product" && (
                  <>
                    <div>
                      <label className="label" htmlFor="prod-name-inp">Product Name</label>
                      <input type="text" id="prod-name-inp" className="input-field" value={productName} onChange={e => setProductName(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="prod-price-inp">Price (USD)</label>
                      <input type="text" id="prod-price-inp" className="input-field" value={productPrice} onChange={e => setProductPrice(e.target.value)} />
                    </div>
                  </>
                )}

                {/* Local Business fields */}
                {schemaType === "local-business" && (
                  <>
                    <div>
                      <label className="label" htmlFor="biz-name-inp">Business Name</label>
                      <input type="text" id="biz-name-inp" className="input-field" value={bizName} onChange={e => setBizName(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="biz-addr-inp">Street Address</label>
                      <input type="text" id="biz-addr-inp" className="input-field" value={bizAddress} onChange={e => setBizAddress(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="biz-phone-inp">Phone Number</label>
                      <input type="text" id="biz-phone-inp" className="input-field" value={bizPhone} onChange={e => setBizPhone(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="biz-url-inp">Website URL</label>
                      <input type="text" id="biz-url-inp" className="input-field" value={bizUrl} onChange={e => setBizUrl(e.target.value)} />
                    </div>
                  </>
                )}

                {/* Review fields */}
                {schemaType === "review" && (
                  <>
                    <div>
                      <label className="label" htmlFor="rev-item-inp">Item / Product Reviewed</label>
                      <input type="text" id="rev-item-inp" className="input-field" value={reviewItem} onChange={e => setReviewItem(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="rev-name-inp">Reviewer Name</label>
                      <input type="text" id="rev-name-inp" className="input-field" value={reviewerName} onChange={e => setReviewerName(e.target.value)} />
                    </div>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                      <div>
                        <label className="label" htmlFor="rev-val-inp">Rating Value (e.g. 4.5)</label>
                        <input type="text" id="rev-val-inp" className="input-field" value={ratingValue} onChange={e => setRatingValue(e.target.value)} />
                      </div>
                      <div>
                        <label className="label" htmlFor="rev-scale-inp">Scale Max (e.g. 5)</label>
                        <input type="text" id="rev-scale-inp" className="input-field" value={bestRating} onChange={e => setBestRating(e.target.value)} />
                      </div>
                    </div>
                  </>
                )}

                {/* Breadcrumb fields */}
                {schemaType === "breadcrumb" && (
                  <div>
                    <label className="label">Breadcrumb Items</label>
                    <div style={{ display: "flex", flexDirection: "column", gap: "8px", maxHeight: "150px", overflowY: "auto", marginBottom: "8px" }}>
                      {breadcrumbs.map((b, idx) => (
                        <div key={idx} style={{ display: "flex", gap: "6px" }}>
                          <input type="text" className="input-field" placeholder="Page Name" value={b.name} onChange={e => {
                            const clone = [...breadcrumbs];
                            clone[idx].name = e.target.value;
                            setBreadcrumbs(clone);
                          }} />
                          <input type="text" className="input-field" placeholder="URL" value={b.url} onChange={e => {
                            const clone = [...breadcrumbs];
                            clone[idx].url = e.target.value;
                            setBreadcrumbs(clone);
                          }} />
                        </div>
                      ))}
                    </div>
                    <button className="btn-secondary" style={{ width: "100%", fontSize: "11px", padding: "4px" }} onClick={() => setBreadcrumbs(prev => [...prev, { name: "", url: "" }])}>
                      ➕ Add Breadcrumb Level
                    </button>
                  </div>
                )}

                {/* Event Fields */}
                {schemaType === "event" && (
                  <>
                    <div>
                      <label className="label" htmlFor="evt-name-inp">Event Name</label>
                      <input type="text" id="evt-name-inp" className="input-field" value={eventName} onChange={e => setEventName(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="evt-date-inp">Start Date</label>
                      <input type="date" id="evt-date-inp" className="input-field" value={eventDate} onChange={e => setEventDate(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="evt-loc-inp">Venue / Address</label>
                      <input type="text" id="evt-loc-inp" className="input-field" value={eventLocation} onChange={e => setEventLocation(e.target.value)} />
                    </div>
                  </>
                )}

                {/* Recipe Fields */}
                {schemaType === "recipe" && (
                  <>
                    <div>
                      <label className="label" htmlFor="rec-name-inp">Recipe Name</label>
                      <input type="text" id="rec-name-inp" className="input-field" value={recipeName} onChange={e => setRecipeName(e.target.value)} />
                    </div>
                    <div>
                      <label className="label" htmlFor="rec-auth-inp">Author Name</label>
                      <input type="text" id="rec-auth-inp" className="input-field" value={recipeAuthor} onChange={e => setRecipeAuthor(e.target.value)} />
                    </div>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
                      <div>
                        <label className="label" htmlFor="rec-prep-inp">Prep Time (ISO, e.g. PT15M)</label>
                        <input type="text" id="rec-prep-inp" className="input-field" value={recipePrepTime} onChange={e => setRecipePrepTime(e.target.value)} />
                      </div>
                      <div>
                        <label className="label" htmlFor="rec-cook-inp">Cook Time (ISO, e.g. PT10M)</label>
                        <input type="text" id="rec-cook-inp" className="input-field" value={recipeCookTime} onChange={e => setRecipeCookTime(e.target.value)} />
                      </div>
                    </div>
                  </>
                )}

                {/* FAQ Fields */}
                {schemaType === "faq" && (
                  <div>
                    <label className="label">FAQ Q&A Rows</label>
                    <div style={{ display: "flex", flexDirection: "column", gap: "8px", maxHeight: "150px", overflowY: "auto", marginBottom: "8px" }}>
                      {faqList.map((item, i) => (
                        <div key={i} style={{ border: "1px solid var(--border)", padding: "8px", borderRadius: "4px", display: "flex", flexDirection: "column", gap: "6px" }}>
                          <input type="text" className="input-field" style={{ fontSize: "12px", padding: "4px 8px" }} placeholder="Question" value={item.q} onChange={e => {
                            const clone = [...faqList];
                            clone[i].q = e.target.value;
                            setFaqList(clone);
                          }} />
                          <input type="text" className="input-field" style={{ fontSize: "12px", padding: "4px 8px" }} placeholder="Answer" value={item.a} onChange={e => {
                            const clone = [...faqList];
                            clone[i].a = e.target.value;
                            setFaqList(clone);
                          }} />
                        </div>
                      ))}
                    </div>
                    <button className="btn-secondary" style={{ width: "100%", fontSize: "12px", padding: "4px" }} onClick={() => setFaqList(prev => [...prev, { q: "", a: "" }])}>
                      ➕ Add Q&A Row
                    </button>
                  </div>
                )}

                <div style={{ marginTop: "12px" }}>
                  <button className="btn-secondary" style={{ width: "100%", justifyContent: "center" }} onClick={() => copyToClipboard(generatedSchemaText)}>
                    📋 Copy Schema Script Code
                  </button>
                </div>
              </div>
            </div>

            {/* Validator tester */}
            <div>
              <h4 style={{ color: "var(--primary-light)", fontSize: "14px", borderBottom: "1px solid var(--border)", paddingBottom: "6px", marginBottom: "12px", textTransform: "uppercase" }}>
                🔬 Rich Results Schema Tester
              </h4>
              <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
                <div>
                  <label className="label" htmlFor="schema-test-inp">Paste JSON-LD Schema String</label>
                  <textarea
                    id="schema-test-inp"
                    className="input-field"
                    rows="6"
                    value={testSchemaInput}
                    onChange={e => setTestSchemaInput(e.target.value)}
                    placeholder="Paste schema script content to validate JSON-LD tags..."
                  />
                </div>
                <button className="btn-primary" onClick={testSchemaSyntax} style={{ justifyContent: "center" }}>
                  ⚡ Validate Schema
                </button>

                {schemaTestResult && (
                  <div style={{
                    padding: "10px",
                    background: schemaTestResult.includes("Valid") ? "rgba(76,175,80,0.15)" : "rgba(244,67,54,0.15)",
                    border: schemaTestResult.includes("Valid") ? "1px solid #4caf50" : "1px solid #f44336",
                    borderRadius: "4px",
                    textAlign: "center",
                    fontWeight: 600,
                    fontSize: "13px",
                    color: schemaTestResult.includes("Valid") ? "#81c784" : "#ef5350"
                  }}>
                    {schemaTestResult}
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </ToolLayout>
  );
}

export default SiteConfigurationStudio;
export { SCHEMA_TYPES };
